### ISSUE TITLE
Email verification and finish up endpoints

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-backend#12]
**Tasks**
- [x] Build orders endpoints.
- [x] Build receipt endpoints.
- [x] Wire up email verification.
