### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-backend#3]
**Feature Description**
A user should be able to create an account on the platform and login.

**Tasks**
- [x] Create a [app.properties](https://github.com/BuildForSDG/.github/blob/master/app.properties) file in root of repo and fill details
- [ ] Setup Flask env
- [ ] Install PyLint
- [ ] Build a register endpoint
- [ ] Valite register input data
- [ ] Build a login endpoint
- [ ] Validate login input data
- [ ] Authenticate with JWT
- [ ] Build reset password endpoint
- [ ] Wire up email verification

**Additional Context**
branch `ft-authentication-endpoints`

**Comment by Dave-mash** [comment]
Please don't close an unapproved issue.

**Comment by moseti1** [comment]
Alright

**Comment by Dave-mash** [comment]
> Alright

Review the pr

**Comment by Dave-mash** [comment]
Redundant
