### ISSUE TITLE
Authentication backend

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-backend#5]
**Feature Description**
A user should be able to create an account on the platform and login.

**Tasks**
- [x] Create a [app.properties](https://github.com/BuildForSDG/.github/blob/master/app.properties) file in root of repo and fill details
- [x] Setup Flask env
- [x] Install PyLint
- [x] Build a register endpoint
- [x] Valite register input data
- [x] Build a login endpoint
- [x] Validate login input data
- [x] Authenticate with JWT
- [ ] Build reset password endpoint
- [ ] Wire up email verification

**Additional Context**
branch `ft-authentication-endpoints`
