### ISSUE TITLE
Build products, comments, orders, and cart endpoints

### ISSUE THREAD

**Issue by Dave-mash** [BuildForSDGCohort2/Team-254-zaoBora-backend#9]
**Tasks**
- [x] Build Products endpoints.
- [x] Build Comments endpoints.
- [ ] Build Orders endpoints.
- [ ] Build Cart endpoints.
- [x] Begin testing the endpoints.
